### ISSUE TITLE
Update Filter Behavior for Dining Menu

### ISSUE THREAD

**Issue by a6wu** [UCSD/campus-mobile#488] opened 2019-05-16 14:05 UTC
### Issue Description

The filter for Vegetarian meals does not display Vegan meals.

### Steps to Reproduce / Code Snippets

On the dining menu for 64 Degrees location, when tapping on Vegetarian, meals that are Vegan are not displayed. Vegan meals are also Vegetarian meals.

#### Expected Results

When the Vegetarian filter is selected, Vegan meals should also display. 

### Additional Information

* React Native version: All
* Platform(s) (iOS, Android, or both?): both
* Operating System (macOS, Linux, or Windows?): N/A

**Comment by c3bryant** [comment] 2019-05-16 16:14
This issue was reviewed in #150 and the root cause was found to be on the service provider's end. The service provider was informed and corrected the issues at that time. Moving this to the internal board as there is no work to be done on our end.

https://its-pro.ucsd.edu/browse/MA-45

**Closed by c3bryant** 2019-05-16 16:14 UTC
Labels: Bug
