### ISSUE TITLE
Delete MobilePlatform-Messages v2

### ISSUE THREAD

**Issue by a6wu** [UCSD/campus-mobile#1080] opened 2020-11-03 21:11 UTC
ITS-Pro time category: https://its-pro.ucsd.edu/browse/MA-69

This is complete when:

- [ ] https://api-qa.ucsd.edu/store/apis/info?name=MobilePlatform-Messages&version=2.0.0&provider=mcmuniz has been deleted

**Comment by c3bryant** [comment] 2020-11-04 18:03
Duplicate of #971

**Closed by c3bryant** 2020-11-04 18:03 UTC
