### ISSUE TITLE
Notifications Feed Content out of Sync with Push Notification

### ISSUE THREAD

**Issue by a6wu** [UCSD/campus-mobile#407] opened 2019-01-29 21:43 UTC
The message content should be available in the notifications feed at the time the push notification is received by the device.

**Comment by g9singh** [comment] 2019-02-16 03:31
A side affect of fixing this issue this is the message just appearing into the list after a few seconds of the push notification being opened without the activity indicator spinning as the message is being fetched.
Root of the issue has to do with UPDATE_MESSAGES saga being called too many times when the FlatList is rendered. 
Another way to solve the issue is to create two separate boolean that handle the reloading and pagination respectively.
This way we can use an activity spinner in place of the FlatList default activity spinner when data is being fetched and populated

**Comment by g9singh** [comment] 2019-02-20 17:46
Another side affect of fixing this issue is the badge indicator no longer functions properly after logging in. The lastSeenTimeStamp is no longer stored on profile. It is stored in state and is cleared once the user logs out.

**Comment by g9singh** [comment] 2019-02-21 17:02
completed:
9e31be3f85abfd978dfed4691f16edcee8bc798e
4c76e710b96a0e107bd1d89ff6a0db92eb87d8c8
7ee32dd21e2e5abe4208e86975984648e1058726
4eed98d8b526fb4137db19cbf241f60d716f22c8

**Comment by g9singh** [comment] 2019-02-22 22:06
The root of the issue was the UPDATE_MESSAGES saga being called too many times. 
Removed one extra call in pushNotificationContainer.js in commit: 7ee32dd21e2e5abe4208e86975984648e1058726
Other extra call is made because the data saga syncs user profile every minute. Need to further discuss if we still want this sync. (Left this untouched for now)

**Comment by c3bryant** [comment] 2019-03-04 19:14
Failed on branch `deep-linking` with one issue

1) Install the app from scratch, do not login, and goto the Notifications tab. Messages will not load unless user action is taken (pull to refresh):
![deep-linking-1](https://user-images.githubusercontent.com/15112294/53756656-8af2bf80-3e6e-11e9-8bba-506709499888.png)

**Comment by g9singh** [comment] 2019-03-05 00:12
Resolved in f458e05da697f42a71e2a743312cdde32b100397

**Comment by c3bryant** [comment] 2019-03-05 22:44
Verified on branch `deep-linking`

**Closed by c3bryant** 2019-03-05 22:44 UTC
Labels: Bug, Ready to Deploy
