### ISSUE TITLE
Share events bug

### ISSUE THREAD

**Issue by g9singh** [UCSD/campus-mobile#560] opened 2019-08-22 17:42 UTC
### Issue Description

When we tap on share event and share via iMessage or sms it tries to attach the entire app in the message. (Specifically the cross culture block party event)

When sharing other events via iMessage or sms the url is duplicated

### Steps to Reproduce / Code Snippets

1) go to an event (cross culture block party event)
2) share it via sms or iMessage
3) wait for the message to send and try to open it on the other device
![Image from iOS.png](https://images.zenhubusercontent.com/5b7c4f70c76bd14ae4d85c98/c33b864f-7b1d-4864-ba38-72987fd7c176)
![Image from iOS (1).png](https://images.zenhubusercontent.com/5b7c4f70c76bd14ae4d85c98/b1505868-4291-405a-b09f-42c68ffcffb9)
#### Expected Results

When we share events it should only share the title and the link to the event itself

### Additional Information
V6.8+

**Comment by vishant101** [comment] 2019-08-23 15:57
Was unable to reproduce the bug on android on a number of different messaging platforms including sms, Facebook messenger, slack and copying to the clip board. Sharing seemed to work fine. 

Assigning this to you @g9singh to check if you can reproduce this on iOS.

**Comment by c3bryant** [comment] 2020-04-10 18:00
This issue is being closed due to platform migration and may be revisited at a later date.

**Closed by c3bryant** 2020-04-10 18:00 UTC
Labels: Bug
