### ISSUE TITLE
Images incorrectly sized and inconsistencies between Iphone versions

### ISSUE THREAD

**Issue by kennytrand** [UCSD/campus-mobile#730] opened 2020-06-03 05:00 UTC
General Problems (Iphone X, Iphone 6, and Iphone 7):
1) Links cannot be copied from detailed view in the event’s card, so users can’t access these websites.
2) The picture for “CAPS Relaxation Skills” is not sized correctly (black bars) in detailed view.
3) The picture for “Transitioning Out of Social Justice Spaces” is not sized correctly in detailed view.
4) The picture for “CAPS Coming Out Group” is not sized correctly in detailed view.
5) The picture for “Circus Circuit with Jacquie” is not centered correctly in detailed view.

Specific Problems
1) The picture for “APIMEDA Community Forum” doesn’t load in detailed view on an Iphone X but does load on an Iphone 6 & 7 however the image is not sized correctly.
2) The picture for “New Podcast: Triton Tools & Tidbits” doesn’t load on in detailed view on an Iphone X but does load on an Iphone 6 & 7 however the image is not sized correctly..
3) The first two PREVIEW event images, “Zoom Live” & “APIMEDA” does not appear on an Iphone 6, however, every other preview image does (every preview image appears on Iphone X & 7).

Suggestions:
1) The text is not aligned with the header in the classes card (Every other card’s text is aligned with the header except this one). 
2) Move or reduce font size for “last updated” status in the classes card somewhere else or reduce font size since it is to cluttered.
3) Make the event’s card similar to the news card so students can open up the links directly from the detailed view

IOS: Iphone 6, 7, an X

**Comment by c3bryant** [comment] 2020-06-09 17:27
Thanks @kennytrand for this detailed review.
All items reported have been moved to or updated in separate issues:

General Problems (Iphone X, Iphone 6, and Iphone 7):
1) Links cannot be copied from detailed view in the event’s card, so users can’t access these websites.
- Dupe of #711

2) The picture for “CAPS Relaxation Skills” is not sized correctly (black bars) in detailed view.
3) The picture for “Transitioning Out of Social Justice Spaces” is not sized correctly in detailed view.
4) The picture for “CAPS Coming Out Group” is not sized correctly in detailed view.
5) The picture for “Circus Circuit with Jacquie” is not centered correctly in detailed view.
- Added #742 for 2-5

Specific Problems
1) The picture for “APIMEDA Community Forum” doesn’t load in detailed view on an Iphone X but does load on an Iphone 6 & 7 however the image is not sized correctly.
2) The picture for “New Podcast: Triton Tools & Tidbits” doesn’t load on in detailed view on an Iphone X but does load on an Iphone 6 & 7 however the image is not sized correctly..
3) The first two PREVIEW event images, “Zoom Live” & “APIMEDA” does not appear on an Iphone 6, however, every other preview image does (every preview image appears on Iphone X & 7).
- Added #743 for 1-3

Suggestions:
1) The text is not aligned with the header in the classes card (Every other card’s text is aligned with the header except this one). 
- Dupe of #715

2) Move or reduce font size for “last updated” status in the classes card somewhere else or reduce font size since it is to cluttered.
- Added to #715

3) Make the event’s card similar to the news card so students can open up the links directly from the detailed view
- Added ##744

**Closed by c3bryant** 2020-06-09 17:27 UTC
Labels: UI/UX
