### ISSUE TITLE
Update BuildingStatus API Subscription

### ISSUE THREAD

**Issue by a6wu** [UCSD/campus-mobile#1615] opened 2021-10-01 18:37 UTC
Time tracking: https://www.speedchecker.com/broadband-data/measurement-method.html

This is complete when the:
- [ ] subscription to the BuildingStatus API limited to authenticated users

**Comment by c3bryant** [comment] 2021-10-04 16:42
Dupe of #1613

**Closed by c3bryant** 2021-10-04 16:42 UTC
