### ISSUE TITLE
Availability Card: Reduce Vertical Scroll Height

### ISSUE THREAD

**Issue by c3bryant** [UCSD/campus-mobile#864] opened 2020-07-29 14:44 UTC
Time Tracking: https://its-pro.ucsd.edu/browse/MA-42

Vertically scrollable content inside an already scrollable Home view is catch is catching users off guard, resulting in a less optimal user experience. Reduce the chance users will find themselves scrolling within a scrollview by limiting the vertical scroll height UI to 1.5 results.

This is done when:
- [x] Availability card inner content height is limited to allow for 1.5 availability results to display

**Comment by woznaut** [comment] 2020-07-30 16:55
there is no solution that will eliminate the requirement of scroll within scroll. the issue is that we need to accommodate locations that may have multiple records (Geisel for example) - since the card height must be fixed so that users can page through multiple cards there would be a need to fix the height at the location with the largest number of records - not really feasible since most locations don't have that many records to display.

the issue that can be addressed is that currently the scroll area within the card is too large. the scroll area needs to be just big enough to show ~1.5 records. reducing the size of the scrollable area will improve the scrolling experience for the home view
![availability](https://user-images.githubusercontent.com/19195410/88951414-cacbfb00-d24a-11ea-9458-b85f401ce67b.png)
.

**Comment by Atreto76** [comment] 2020-08-11 20:36
A change made in a pending PR has been utilized to solve this issue so the fix is included in that PR.

**Closed** 2020-10-10 14:07 UTC
