### ISSUE TITLE
UI Unresponsive with Scroll Issue

### ISSUE THREAD

**Issue by a6wu** [UCSD/campus-mobile#1026] opened 2020-10-13 15:53 UTC
ITS-Pro time category: https://its-pro.ucsd.edu/projects/MA/issues/MA-34?filter=allopenissues

Could not reproduce, but when the app launched, the UI was unresponsive. Was not able to tap down into any details or features. Data was displayed in the cards. Scrolling down displayed more white background above the first card and scrolling up displayed white background after the last card.

This is complete when:

- [ ] The issue can be reproduced
- [ ] A fix is implemented

![image.png](https://images.zenhubusercontent.com/5a714b9f4b5806bc2bc4fcb0/be7b4f14-1b13-4f65-a198-99086bbc8a21)

![image.png](https://images.zenhubusercontent.com/5a714b9f4b5806bc2bc4fcb0/ba8a9523-c916-4530-a275-efa7a623ae60)

**Comment by kevdesilva01** [comment] 2020-10-20 17:11
@a6wu do you know which version this was in? I see that the TWOW banner is up for these screenshots.

**Comment by a6wu** [comment] 2020-10-20 19:14
@kevdesilva01 I believe it was Prod. TWOW was a special event that has since passed and will no longer be seen in the app. If you cannot reproduce with different approaches with the app, then we can table this issue.

**Comment by kevdesilva01** [comment] 2020-10-22 15:00
@a6wu I've been unable to reproduce the issue. I think we can close this out but I'll just always keep an eye out if I ever run into this bug somehow.

**Closed** 2020-10-22 15:12 UTC
Labels: Bug
