### ISSUE TITLE
Student ID Card: Card on Home View

### ISSUE THREAD

**Issue by a6wu** [UCSD/campus-mobile#443] opened 2019-03-11 23:35 UTC
Implement Image, name, college, major, barcode in a card format; store data locally in the app

**Comment by a6wu** [comment] 2019-03-11 23:41
https://collab.ucsd.edu/display/WTS/Student+ID+Card

**Comment by a6wu** [comment] 2019-03-15 20:50
Task Breakdown:

1. Finalize UI mockup for v1; alternate version w/ title, elipsis
2. Implement codabar generator
3. Implement Image, name, college, major, barcode in a card format
4. Implement student status
5. Store data locally in app
6. Add card to settings view for toggling on/off and reordering

**Comment by g9singh** [comment] 2019-03-18 16:10
https://github.com/c19354837/react-native-system-setting
https://www.npmjs.com/package/react-native-device-brightness
These libraries can help us change brightness on devices when user displays the barcode

**Comment by c3bryant** [comment] 2019-04-10 17:16
Todo:
- [ ] Back button on Android should close barcode modal
- [ ] Add swipe to close demo
- [ ] Decrease enlarged barcode size by 15%
- [ ] Decrease modal size by 15%
- [ ] Use barcode id from MyStudentProfile API

**Comment by g9singh** [comment] 2019-05-23 22:00
Two branches have been made for this issue:

feature/student-id-card: 2cb59476e8ef14641d9766123b29ea58b7a54786
This branch is the version where the student ID card data is fetched and combined by the mobile client (four api calls).

feature/student-id-card-lambda: f2f3dbc905053dd0ef71e24cd24276d3fb1097cd
This branch is the version where the student ID card data is combined and generated by a lambda. The mobile client only makes one call in this case.

Things that still need to be completed: 
-What to show/do when partial data returned by any of the api calls?
-Do we want to show a refresh button?
-Do we want to show partial data or just a loading indicator till all the api's return something?

@c3bryant sending your way for initial testing and comments

**Comment by g9singh** [comment] 2019-05-31 19:26
We decided to move forward with the feature/student-id-card branch. This is the branch that has the client call four apis and combine data. 

Changes made:
Added a time out for the network request 
Added a "Try again" button to allow user to refetch data incase of failure
Handled partial data issue 
Fixed infinite loading issue

commit: 3f940254b882a0322ab71fe1630e5fe053fd9367

**Comment by g9singh** [comment] 2019-06-05 21:28
Added a 1 day TTL for the student ID card 
Fixed Try again button to only load if error occurs and not on initial launch 
Added migration code so user who are already logged in will see the card right after updating 

latest commit on feature/student-id-card branch: 928da424d1208a78c6d712658c53ff51d25645ad

The reason for adding the TTL is because we ran into issues while trying to make fetch calls on app launch. We believe the issue is similar to the one stated in the following link: https://stackoverflow.com/questions/49839869/saga-not-running-when-action-creator-being-called-inside-componentdidmount

**Comment by c3bryant** [comment] 2019-06-06 05:14
Initial testing passing on Android and iOS, merged into `6.7`

**Closed by c3bryant** 2019-06-06 05:14 UTC
Labels: Ready for Prod
